# see https://github.com/rmoff/debezium-ccloud/blob/master/docker-compose.yml
version: '3.8'
services:
  sqlserver-connect:
    container_name: sqlserver-connect
    image: core-harbor.lighthouse.jhc.uk/platform-of-apps/sqlserver-connect:2.0.0.final-1
    expose:
        - 8085
    ports:
        - "8085:8083"
    environment:
      - GROUP_ID=sqlserver-debezium

      - CONNECT_REST_ADVERTISED_HOST_NAME=sqlserver-connector
      - CONNECT_REST_ADVERTISED_PORT=8083
      - CONNECT_REST_HOST_NAME=0.0.0.0
      - CONNECT_REST_PORT=8083

      - CONNECT_TASK_SHUTDOWN_GRACEFUL_TIMEOUT_MS=10000

      - BOOTSTRAP_SERVERS=${BOOTSTRAP_SERVERS}
      - CONNECT_CLIENT_DNS_LOOKUP=use_all_dns_ips
      - CONNECT_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="${KAFKA_KEY}" password="${KAFKA_SECRET}";
      - CONNECT_SASL_MECHANISM=PLAIN
      - CONNECT_SECURITY_PROTOCOL=SASL_SSL

      - CONNECT_AUTO_CREATE_TOPICS_ENABLE=true
      - CONNECT_CONSUMER_REQUEST_TIMEOUT_MS=20000
      - CONNECT_CONSUMER_RETRY_BACKOFF_MS=500

      - CONNECT_PLUGIN_PATH=/kafka/connect

      - OFFSET_STORAGE_TOPIC=sqlserver_debezium_offset
      - STATUS_STORAGE_TOPIC=sqlserver_debezium_status
      - CONFIG_STORAGE_TOPIC=sqlserver_debezium_config

      - TOPIC_CREATION_DEFAULT_REPLICATION_FACTOR=3

      - CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR=3
      - CONNECT_OFFSET_STORAGE_PARTITIONS=5
      - CONNECT_OFFSET_FLUSH_INTERVAL_MS=60000
      - CONNECT_OFFSET_FLUSH_TIMEOUT_MS=5000
      - CONNECT_OFFSET_STORAGE_FILE_FILENAME=/tmp/connect.offset

      - CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR=3
      - CONNECT_CONFIG_STORAGE_RPARTITIONS=1
      - CONNECT_STATUS_STORAGE_REPLICATION_FACTOR=3
      - CONNECT_STATUS_STORAGE_PARTITIONS=1
      - CONNECT_TOPIC_CREATION_SQLSERVER_DEBEZIUM_OFFSET_CLEANUP_POLICY=compact

      - CONNECT_CONSUMER_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="${KAFKA_KEY}" password="${KAFKA_SECRET}";
      - CONNECT_CONSUMER_SASL_MECHANISM=PLAIN
      - CONNECT_CONSUMER_SECURITY_PROTOCOL=SASL_SSL
      - CONNECT_CONSUMER_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=https
      - CONNECT_PRODUCER_BATCH_SIZE=327680
      - CONNECT_PRODUCER_REQUEST_TIMEOUT_MS=20000
      - CONNECT_PRODUCER_RETRY_BACKOFF_MS=500
      - CONNECT_PRODUCER_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="${KAFKA_KEY}" password="${KAFKA_SECRET}";
      - CONNECT_PRODUCER_SASL_MECHANISM=PLAIN
      - CONNECT_PRODUCER_SECURITY_PROTOCOL=SASL_SSL
      - CONNECT_PRODUCER_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=https

      - CONNECT_INTERNAL_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - CONNECT_INTERNAL_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter

      - CONNECT_SCHEMA_REGISTRY_URL=${SCHEMA_REGISTRY}
      - CONNECT_BASIC_AUTH_CREDENTIALS_SOURCE=USER_INFO

      - KEY_CONVERTER=io.confluent.connect.avro.AvroConverter
      - VALUE_CONVERTER=io.confluent.connect.avro.AvroConverter

      - CONNECT_KEY_CONVERTER_BASIC_AUTH_CREDENTIALS_SOURCE=USER_INFO
      - CONNECT_KEY_CONVERTER_BASIC_AUTH_USER_INFO=${SCHEMA_KEY}:${SCHEMA_SECRET}
      - CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE=true
      - CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL=${SCHEMA_REGISTRY}
      - CONNECT_VALUE_CONVERTER_BASIC_AUTH_CREDENTIALS_SOURCE=USER_INFO
      - CONNECT_VALUE_CONVERTER_BASIC_AUTH_USER_INFO=${SCHEMA_KEY}:${SCHEMA_SECRET}
      - CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE=true
      - CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL=${SCHEMA_REGISTRY}

      # - JAVA_TOOL_OPTIONS=-Djava.security.debug=all